config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "tasks", to: "tasks#index", as: :tasks
  get "task/:id", to: "tasks#show", as: :task
  get "tasks/new", to: "tasks#new", as: :new_task
  post "tasks", to: "tasks#create", as: :create
  get "tasks/:id/edit", to: "tasks#edit", as: :edit
  patch "task/:id", to: "tasks#update", as: :update
  delete "tasks/:id", to: "tasks#destroy", as: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end
  def show
    @task = Task.find(params[:id])
  end
  def new
    @task = Task.new
  end
  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end
  def edit
    @task = Task.find(params[:id])
  end
  def update
  @task = Task.find(params[:id])
  @task.update(task_params)
  redirect_to task_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit a Task</h1>
<%= form_for(@task) do |t| %>
  <ul>
  <% @task.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= t.label :title %><br />
    <%= t.text_field :title %>
  </p>
  <p>
    <%= t.label :details %><br />
    <%= t.text_area :details %>
  </p>
  <p>
    <%= t.submit %>
  </p>
<% end %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>


<ul id="tasks">
  <% @tasks.each do |task| %>
    <li>
      <%= link_to task.title, task_path(task) %>
    </li>
  <% end %>
</ul>
<%= link_to "Add a new Task", new_task_path, class: "new_task" %>

app/views/tasks/new.html.erb
<h1>Add a New Task</h1>
<%= form_for(@task) do |t| %>
  <ul>
  <% @task.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= t.label :title %><br />
    <%= t.text_field :title %>
  </p>
  <p>
    <%= t.label :details %><br />
    <%= t.text_area :details %>
  </p>
  <p>
    <%= t.submit %>
  </p>
<% end %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>

<% if @task.completed %>
 <p>[X] This task is completed </p>
<% else %>
 <p>[ ] This task is not completed </p>
<% end  %>
<%= link_to "Back to list", tasks_path %>
<%= link_to "delete", destroy_path(@task), method: :delete %>
<%= link_to "edit", edit_path %>